site_name: D7 to D8 Examples
pages:
- 'Home': index.md
- 'Front End': 
  - 'Summary': front-end/index.md
- 'Back End':
  - 'Summary': back-end/index.md
  - 'Blocks': back-end/blocks.md
- 'Site Building': site-building/index.md
- 'Miscelleneous': misc/index.md
- 'Contributing': contributing.md